INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000001', '삽살개', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000002', '코리아 트라이 하운드', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000003', '풍산견', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000004', '아프간 하운드', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000005', '에어델 테리어', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000006', '아키다', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000007', '알라스칸 말라뮤트', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000008', '아메리칸 아키다', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000009', '아메리칸 코카 스파니엘', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000010', '오스트랄리안 캐틀 독', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000011', '오스트랄리안 셰퍼드 독', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000012', '바셋 하운드', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000013', '비글', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000014', '비어디드 콜리', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000015', '베들링턴 테리어', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000017', '버니즈 마운틴 독', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000018', '비숑 프리제', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000019', '블랙 테리어', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000020', '보더 콜리', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000021', '보르조이', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000022', '보스턴 테리어', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000023', '부비에 데 플랑드르', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000024', '복서', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000025', '브리타니 스파니엘', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000027', '불독', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000028', '카네 코르소', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000029', '케니스펜더', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000030', '캐벌리어 킹 찰스 스파니엘', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000031', '센트럴 아시안 오브차카', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000032', '치와와', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000033', '차이니즈 크레스티드 독', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000034', '샤페이', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000035', '차우차우', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000037', '꼬똥 드 뚤레아', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000038', '스탠다드 닥스훈트', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000039', '달마시안', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000040', '댄디 딘몬트 테리어', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000041', '도베르만', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000042', '도고 아르젠티노', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000043', '도고 까니리오', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000044', '잉글리쉬 코카 스파니엘', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000045', '잉글리쉬 포인터', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000046', '잉글리쉬 세터', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000047', '잉글리쉬 스프링거 스파니엘', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000048', '필라 브라질레이로', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000049', '플랫 코티드 리트리버', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000050', '프렌치 불독', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000052', '저먼 셰퍼드 독', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000053', '자이언트 슈나우져', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000054', '골든 리트리버', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000055', '그레이트 덴', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000056', '그레이 하운드', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000057', '아이리쉬 세터', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000058', '아이리쉬 울프 하운드', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000059', '아이리쉬 소프트 코티드 휘튼 테리어', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000060', '이탈리안 그레이 하운드', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000061', '잭 러셀 테리어', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000062', '재패니즈 스피츠', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000063', '키스 훈드', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000064', '케리 블루 테리어', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000065', '키슈', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000066', '클라인스피츠', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000067', '진도견', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000068', '코리안 마스티프', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000069', '라브라도 리트리버', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000070', '레이크랜드 테리어', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000071', '라사 압소', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000072', '말티즈', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000073', '마스티프', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000074', '미디엄 푸들', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000075', '미니어쳐 불 테리어', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000076', '미니어쳐 닥스훈트', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000077', '미니어쳐 핀셔', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000078', '미니어쳐 푸들', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000079', '미니어쳐 슈나우저', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000080', '미텔 스피츠', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000081', '네오폴리탄 마스티프', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000082', '뉴펀들랜드', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000083', '노리치 테리어', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000084', '올드 잉글리쉬 쉽독', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000085', '빠삐용(콘티넨탈 토이 스파니엘)', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000086', '파슨 러셀 테리어', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000087', '페키니즈', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000088', '팔렌(콘티넨탈 토이 스파니엘)', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000089', '포메라니안', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000090', '퍼그', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000091', '풀리', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000092', '피레니안 마운틴 독', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000093', '래빗 닥스훈트', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000094', '로트와일러', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000095', '살루키', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000096', '사모예드', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000097', '스코티쉬 테리어', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000098', '실리햄 테리어', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000099', '셔틀랜드 쉽독', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000100', '시바', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000101', '시츄', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000102', '시코쿠', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000103', '시베리안 허스키', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000104', '세인트 버나드', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000105', '스탠다드 푸들', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000106', '티베탄 마스티프', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000107', '토이 푸들', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000108', '웰시 코기 펨브로크', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000109', '웰시 테리어', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000110', '웨스트하이랜드화이트테리어', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000111', '휘펫', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000112', '폭스 테리어(와이어)', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000113', '요크셔 테리어', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000114', '믹스견', '개', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000115', '기타', '개', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000116', '고양이', '고양이', '단모종');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000117', '기타축종', '기타', '기타');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000118', '그레이트 피레니즈', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000119', '아메리칸 핏불 테리어', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000120', '도사', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000121', '로트와일러', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000122', '셰퍼드', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000123', '슈나우져', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000124', '스피츠', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000125', '코카 스파니엘', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000128', '미확인', '개', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000129', '제페니즈칭', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000130', '화이트리트리버', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000131', '아메리칸 에스키모', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000132', '스코티시 디어하운드', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000133', '바센지', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000134', '화이트테리어', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000135', '핏불테리어', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000136', '실키테리어', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000137', '올드 잉글리쉬 불독', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000138', '페터데일테리어', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000139', '시잉프랑세즈', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000140', '토이 맨체스터 테리어', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000141', '코카 푸', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000143', '오브차카', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000144', '카이훗', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000145', '코카시안 오브차카(코카시안 셰퍼드 독)', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000146', '말라뮤트', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000147', '플롯하운드', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000148', '벨기에 테뷰런', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000149', '울프독', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000150', '아메리칸불리', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000152', '마리노이즈', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000153', '도고 아르젠티노', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000154', '스태퍼드셔 불 테리어', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000155', '동경견', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000156', '제주개', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000157', '벨기에 쉽독', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000158', '카레리안 베어독', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000159', '맨체스터테리어', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000160', '아메리칸 불독', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000161', '프레사까나리오', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000162', '비즐라', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000163', '와이마라너', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000164', '벨지안 셰퍼드 독(그로넨달)', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000165', '저먼 와이어헤어드 포인터', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000166', '로디지안 리즈백 ', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000167', '랫 테리어', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000168', '프렌치 브리타니', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000169', '브뤼셀그리펀', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000170', '노르웨이 숲', '고양이', '장모종');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000171', '데본 렉스', '고양이', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000172', '러시안 블루', '고양이', '단모종');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000173', '레그돌-라가머핀', '고양이', '장모종');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000174', '맹크스', '고양이', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000175', '먼치킨', '고양이', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000176', '메인쿤', '고양이', '장모종');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000177', '발리네즈', '고양이', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000178', '버만', '고양이', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000179', '벵갈', '고양이', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000180', '봄베이', '고양이', '단모종');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000181', '브리티시 쇼트헤어', '고양이', '단모종');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000182', '사바나캣', '고양이', '장모종');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000183', '샤트룩스', '고양이', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000184', '샴', '고양이', '단모종');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000185', '셀커크 렉스', '고양이', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000186', '소말리', '고양이', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000187', '스노우 슈', '고양이', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000188', '스코티시폴드', '고양이', '단모종');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000189', '스핑크스', '고양이', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000190', '시베리안 포레스트', '고양이', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000191', '싱가퓨라', '고양이', '단모종');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000192', '아메리칸 쇼트헤어', '고양이', '단모종');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000193', '아비시니안', '고양이', '단모종');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000194', '재패니즈밥테일', '고양이', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000195', '터키시 앙고라', '고양이', '장모종');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000196', '통키니즈', '고양이', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000197', '페르시안-페르시안 친칠라', '고양이', '장모종');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000198', '하바나 브라운', '고양이', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000199', '하일랜드 폴드', '고양이', '장모종');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000200', '한국 고양이', '고양이', '단모종');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000201', '기타', '고양이', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000202', '아나톨리안 셰퍼드', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000203', '아메리칸 스태퍼드셔 테리어', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000204', '노르포크 테리어', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000205', '웰시 코기 카디건', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000206', '허배너스', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000207', '케언 테리어', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000208', '볼로네즈', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000209', '파라오 하운드', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000210', '아이리쉬 레드 앤 화이트 세터', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000212', '믹스묘', '고양이', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000216', '브리티쉬롱헤어', '고양이', '장모종');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000217', '오스트레일리안 켈피', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000218', '니벨룽', '고양이', '그외');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000219', '도사 믹스견', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000220', '아메리칸 핏불 테리어 믹스견', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000221', '아메리칸 스태퍼드셔 테리어 믹스견', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000222', '스태퍼드셔 불 테리어 믹스견', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000223', '로트와일러 믹스견', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000224', '핏불테리어 믹스견', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000225', '벨지안 셰퍼드 독(라케노이즈)', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000226', '벨지안 셰퍼드 독(마리노이즈)', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000227', '벨지안 셰퍼드 독(테르뷰렌)', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000228', '러프콜리', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000229', '스무스콜리', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000230', '저먼 쇼트헤어드 포인터', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000231', '이스트 시베리언 라이카', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000232', '유쿠시안 라이카', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000233', '스키퍼키', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000234', '체코슬로바이칸 울프독', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000235', '화이트 스위스 세퍼드', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000236', '오스트레일리안 케틀독', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000237', '아펜핀셔', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000238', '중앙아시안 셰퍼드', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000239', '캉갈 셰퍼드 독', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000240', '폭스 테리어(스무스)', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000241', '케리블루 테리어', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000242', '케나디언 에스키모 독', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000243', '타이 리지벡 독', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000244', '프티 바세 그리퐁 방댕', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000245', '고든 세터', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000246', '웰시 스프링어 스패니얼', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000247', '라고토 로마그놀로', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000248', '포르투갈 워터 도그', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000249', '그리펀 벨지언', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000250', '제페니스 친', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000251', '러시안 토이', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000252', '아자와크', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('000253', '슬루기', '개', '대형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('00213', '레그돌', '고양이', '장모종');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('00214', '페르시안', '고양이', '장모종');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('00216', '노퍽 테리어', '개', '소형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('211', '웨스트 시베리언 라이카', '개', '중형견');
INSERT INTO `species` (`kind_id`, `kind_name`, `type_name`, `category`) VALUES ('215', '저먼 헌팅 테리어', '개', '중형견');